name: pysal-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.9
  - mamba
  - pip
  - geopandas
  - descartes
  - folium
  - ipython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - pysal
  - geosnap
  - nbconvert
  - networkx
  - palettable
  - scikit-learn
  - seaborn
  - statsmodels
  - hvplot
  - holoviews
  - geoviews
  - watermark
  - rasterio
  - splot
  - watermark
  - geosnap
